name: CI for React Vite App

on:
  push:
    branches:
      - main
    paths:
      - game-hub/**
  pull_request:
    branches:
      - main
    paths:
      - game-hub/**

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VITE_API_KEY: ${{ secrets.VITE_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Specify the correct working directory where package.json is located
      - name: Install dependencies
        working-directory: ./game-hub
        run: npm install

      - name: Build project
        working-directory: ./game-hub
        run: npm run build
