name: CI for React Vite App

# Run on push and pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs that will run in the workflow
jobs:
  build:
    # The environment where the job will run
    runs-on: ubuntu-latest

    # Set up environment variables, including the API key from GitHub Secrets
    env:
      VITE_API_KEY: ${{ secrets.VITE_API_KEY }}

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js with version 22.4.1
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.4.1" # Set to the version you're using

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run the build process
      - name: Build project
        run: npm run build

      # (Optional) Run a preview to test the build
      # Uncomment if you'd like to run the Vite preview server during the CI process
      # - name: Preview build
      #   run: npm run preview
